# Generated by Django 6.0.2 on 2026-02-08 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tên Module")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Danh sách Module",
            },
        ),
        migrations.CreateModel(
            name="ExamConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Thời gian làm bài (phút). 0 là không giới hạn.",
                        verbose_name="Thời gian (phút)",
                    ),
                ),
                (
                    "show_result_mode",
                    models.CharField(
                        choices=[
                            ("immediate", "Hiển thị ngay sau mỗi câu"),
                            ("after_submit", "Hiển thị sau khi nộp bài"),
                            ("hidden", "Không hiển thị kết quả"),
                        ],
                        default="after_submit",
                        max_length=20,
                        verbose_name="Chế độ hiển thị kết quả",
                    ),
                ),
                (
                    "randomize_questions",
                    models.BooleanField(default=False, verbose_name="Trộn câu hỏi"),
                ),
                (
                    "module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_config",
                        to="quiz.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấu hình bài thi",
                "verbose_name_plural": "Cấu hình bài thi",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung câu hỏi")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Trắc nghiệm 1 đáp án"),
                            ("multiple", "Trắc nghiệm nhiều đáp án"),
                            ("text", "Trả lời ngắn"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Loại câu hỏi",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.module",
                        verbose_name="Thuộc Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Câu hỏi",
                "verbose_name_plural": "Danh sách Câu hỏi",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=255, verbose_name="Nội dung đáp án"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Là đáp án đúng"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quiz.question",
                        verbose_name="Câu hỏi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đáp án",
                "verbose_name_plural": "Danh sách Đáp án",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Bắt đầu"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kết thúc"
                    ),
                ),
                ("score", models.FloatField(default=0.0, verbose_name="Điểm số")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quiz.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Học viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lượt thi",
                "verbose_name_plural": "Lịch sử thi",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(blank=True, to="quiz.choice"),
                ),
            ],
        ),
    ]
