# Generated by Django 6.0.2 on 2026-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="current_question_index",
            field=models.IntegerField(default=0, verbose_name="Câu hỏi hiện tại"),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="question_order",
            field=models.TextField(
                blank=True,
                help_text="Danh sách ID câu hỏi theo thứ tự, ngăn cách bởi dấu phẩy",
                null=True,
            ),
        ),
    ]
